version: '3.5'

services:
  php:
    build:
      context: ./
      dockerfile: .docker/api/Dockerfile
      args:
        - ENABLE_XDEBUG=true
        - XDEBUG_CLIENT_HOST=${XDEBUG_CLIENT_HOST-host.docker.internal}
    image: daily-focus
    container_name: daily-focus
    restart: unless-stopped
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - internal

  web:
    container_name: daily-focus-web
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./.docker/api/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - internal

  mysql:
    container_name: daily-focus-mysql
    image: docker.io/mysql:8.3.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=daily-focus
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=challenge
      - MYSQL_PASSWORD=challenge
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - ./resources/mysql/wait_for_mysql.sh:/tmp/wait_for_mysql.sh
    networks:
      - internal
  
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:
    driver: bridge