# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true

    Doctrine\ORM\EntityManagerInterface: '@doctrine.orm.default_entity_manager'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    DailyFocus\:
        resource: '../../src/'
    DailyFocus\App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/AppKernel.php'
    DailyFocus\Tests\:
      resource: '../../tests'
    DailyFocus\App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    DailyFocus\Product\Domain\ProductRepository:
        class: DailyFocus\Product\Infrastructure\Product\MysqlProductRepository
        arguments:
            - '@doctrine.orm.entity_manager'

    DailyFocus\Discount\Domain\DiscountRepository:
        class: DailyFocus\Discount\Infrastructure\Discount\MysqlDiscountRepository
        arguments:
            - '@doctrine.orm.entity_manager'
    
    DailyFocus\Discount\Infrastructure\DataFixtures\:
        resource: '../../src/Discount/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    DailyFocus\Price\Infrastructure\DataFixtures\:
        resource: '../../src/Price/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    DailyFocus\Product\Infrastructure\DataFixtures\:
        resource: '../../src/Product/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']

    DailyFocus\Category\Infrastructure\DataFixtures\:
        resource: '../../src/Category/Infrastructure/DataFixtures'
        tags: ['doctrine.fixture.orm']